#%RAML 1.0
---

title: Check a UK VAT number
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
  - title: Testing
    content: !include docs/testing.md

/organisations/vat:
    /check-vat-number/lookup:
      /{targetVrn}:
        uriParameters:
          targetVrn:
            description: UK VAT registration number you wish to check. <br> A 9-digit or 12-digit number.
            type: string
            example: "123456789"
        get:
          displayName: Get a VAT registration
          description: Allows retrieval of name and address of a VAT registered company
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
          securedBy: [ sec.x-application ]
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                        "target": {
                            "name":"Credite Sberger Donal Inc.",
                            "vatNumber":"553557881",
                            "address":{
                                "line1":"131B Barton Hamlet",
                                "postcode":"SW97 5CK",
                                "countryCode":"GB"
                                }
                        },
                        "processingDate":"2019-01-31T12:43:17.092"
                    }
            400:
              body:
                application/json:
                  schema: !include "schemas/error.json"
                  description: Invalid request
                  example: |
                    {
                      "code": "INVALID_REQUEST",
                      "message": "Invalid targetVrn - Vrn parameters should be 9 or 12 digits"
                    }
            404:
              body:
                application/json:
                  schema: !include "schemas/error.json"
                  description: Not found
                  example: |
                    {
                      "code": "NOT_FOUND",
                      "message": "targetVrn does not match a registered company"
                    }
            500:
              body:
                application/json:
                  schema: !include "schemas/error.json"
                  description: Internal server error
                  example: |
                    {
                      "code": "INTERNAL_SERVER_ERROR",
                      "message": "Unknown error"
                    }
      /{targetVrn}/{requesterVrn}:
        uriParameters:
          targetVrn:
            description: UK VAT registration number you want to check. <br> A 9-digit or 12-digit number.
            type: string
            example: "123456789"
          requesterVrn:
            description: Your VAT registration number. <br> A 9-digit or 12-digit number.
            type: string
            example: "123456789"
        get:
          displayName: Get a VAT registration with a reference number
          description: Retrieves the name and address of a UK VAT-registered business, if the business exists.
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
          securedBy: [ sec.x-application ]
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                        "target":{
                            "name":"Credite Sberger Donal Inc.",
                            "vatNumber":"553557881",
                            "address":{
                                "line1":"131B Barton Hamlet",
                                "postcode":"SW97 5CK",
                                "countryCode":"GB"
                            }
                        },
                        "requester":"146295999727",
                        "consultationNumber":"ypAeKRPlW",
                        "processingDate":"2019-01-31T12:53:05.205"
                    }
            400:
              body:
                application/json:
                  schema: !include "schemas/error.json"
                  description: Invalid request
                  example: |
                    {
                      "code": "INVALID_REQUEST",
                      "message": "Invalid requesterVrn - Vrn parameters should be 9 or 12 digits"
                    }
            403:
              body:
                application/json:
                  schema: !include "schemas/error.json"
                  description: Invalid request
                  example: |
                    {
                      "code": "INVALID_REQUEST",
                      "message": "requesterVrn does not match a registered company"
                    }
            404:
              body:
                application/json:
                  schema: !include "schemas/error.json"
                  description: Not found
                  example: |
                    {
                      "code": "NOT_FOUND",
                      "message": "targetVrn does not match a registered company"
                    }
            500:
              body:
                application/json:
                  schema: !include "schemas/error.json"
                  description: Internal server error
                  example: |
                    {
                      "code": "INTERNAL_SERVER_ERROR",
                      "message": "Unknown error"
                    }
